[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
gas_reports = ["*"]
fs_permissions = [{ access = "read", path = "utils/"}]

[fuzz]
runs = 10_000
