export const NETWORK = {
  LOCAL: 'localhost',
  HARDHAT: 'hardhat',
  MAINNET: 'ethereum',
  ROPSTEN: 'ropsten',
  RINKEBY: 'rinkeby',
  GOERLI: 'goerli',
  KOVAN: 'kovan',
  BSC: 'bsc',
  POLYGON: 'polygon',
  POLYGON_MUMBAI: 'polygon_mumbai',
  AVALANCHE: 'avalance',
  FANTOM: 'fantom',
  CELO: 'celo',
  OPTIMISM: 'optimism',
  ARBITRUM: 'arbitrum',
  ARBITRUM_GOERLI: 'arbitrum_goerli',
} as const

export const CHAINID = {
  LOCAL: 1337,
  HARDHAT: 1337,
  MAINNET: 1,
  ROPSTEN: 3,
  RINKEBY: 4,
  GOERLI: 5,
  KOVAN: 42,
  BSC: 56,
  POLYGON: 137,
  POLYGON_MUMBAI: 80001,
  AVALANCHE: 43114,
  FANTOM: 250,
  CELO: 42220,
  OPTIMISM: 10,
  ARBITRUM: 42161,
  ARBITRUM_GOERLI: 421613,
} as const
